name: Terraform Rule Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/dac-deployment-automation/**'  # Trigger only if files in secops-dac change

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Store your GCP service account key in GitHub Secrets

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Change to your Terraform version if needed

      - name: Initialize Terraform
        run: |
          cd terraform/dac-deployment-automation
          terraform init \
            -backend-config="bucket=${{ secrets.GCS_BUCKET }}" \
            -backend-config="prefix=terraform/state"

      - name: Apply Terraform Configuration
        run: |
          cd terraform/dac-deployment-automation
          terraform apply -auto-approve \
            -var "secops_instance_region=${{ secrets.SECOPS_INSTANCE_REGION }}" \
            -var "secops_instance_id=${{ secrets.SECOPS_INSTANCE_ID }}" \
            -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}"
